resume/config/routes.rb
Resume::Application.routes.draw do

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

  match '/signup', to: 'users#new'

end

resume/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

resume/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

resume/app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Your Resume"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

resume/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

resume/app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
 		<a href="http://whiteboard.sv.cmu.edu/people/JasonTao/">Your Resume</a>
 		by Jason Tao
	</small>
	<nav>
		<ul>
			<li><%= link_to("About", 	about_path) %></li>
		</ul>
	</nav>	
</footer>

resume/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%=link_to("sample app", root_path, id: "logo") %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to("Home",			root_path)%></li>
					<li><%= link_to("Help",		 	help_path)%></li>
					<li><%= link_to("Sign in",		'#')%></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

resume/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

resume/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resume</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

resume/app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>Hi, my name is Jason Tao and I am learning how to build a website using ruby-on-rails. I think a resume platform is a good option because most of the online resume builder is not quite convenient. I am trying to add some features that I think will be useful. Let's just see how far it can go.</p>
<p>This online resume app is developed by ruby-on-rails</p>

resume/app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Please <a href="taojason@gmail.com">email</a> me if you have any questions or suggestions.</p>

resume/app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Your Resume</h1>
	
	<h2>
		This is the platform one can build up his/her resume and profile information.
	</h2>

	<%= link_to("Sign up now!", '#', class: "btn btn-large btn-primary") %>

</div>

<%= link_to(image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/') %>